
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: request_id
          matcherRegex: '"request_id":\s*"([^"]+)"'
          datasourceUid: loki
          url: '/explore?left={"queries":[{"expr":"{service=\"api\"} |= \"$${__value.raw}\""}]}'
