# RDS PostgreSQL, plus the secret plumbing around it.
#
# The password is generated by Terraform, written straight into Secrets
# Manager, and read from there by ECS at task start. It is never typed by a
# human, never passed as a -var, and never appears in a tfvars file.
#
# It does land in the Terraform state file, which is unavoidable with
# random_password. That is why the state bucket is encrypted, versioned, and
# blocked from public access - the state is treated as a secret itself.

locals {
  tags = merge(var.tags, { Module = "database" })
}

resource "aws_db_subnet_group" "this" {
  name       = "${var.name_prefix}-db"
  subnet_ids = var.subnet_ids

  tags = merge(local.tags, { Name = "${var.name_prefix}-db-subnets" })
}

# Postgres logging turned up so the centralised logging story covers the
# database too, not just the app. log_min_duration_statement is the useful
# one: it logs slow queries without logging every query.
resource "aws_db_parameter_group" "this" {
  name_prefix = "${var.name_prefix}-pg-"
  family      = var.parameter_group_family
  description = "Managed by Terraform for ${var.name_prefix}"

  parameter {
    name  = "log_min_duration_statement"
    value = tostring(var.slow_query_threshold_ms)
  }

  parameter {
    name  = "log_connections"
    value = "1"
  }

  parameter {
    name  = "log_disconnections"
    value = "1"
  }

  parameter {
    name  = "log_lock_waits"
    value = "1"
  }

  lifecycle {
    create_before_destroy = true
  }

  tags = local.tags
}

resource "random_password" "master" {
  length  = 32
  special = true
  # RDS rejects these in a master password; leaving them in produces an
  # InvalidParameterValue at create time that is annoying to trace back.
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_kms_key" "database" {
  count = var.create_kms_key ? 1 : 0

  description             = "Encrypts ${var.name_prefix} RDS storage and its credential secret"
  deletion_window_in_days = 7
  enable_key_rotation     = true

  tags = merge(local.tags, { Name = "${var.name_prefix}-db-kms" })
}

locals {
  # Falls back to the AWS-managed key when no CMK is created. Encryption is
  # never off; the choice is only who owns the key.
  kms_key_id = var.create_kms_key ? aws_kms_key.database[0].arn : null
}

resource "aws_db_instance" "this" {
  identifier = "${var.name_prefix}-postgres"

  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  # gp3 costs the same as gp2 at small sizes but gives a baseline 3000 IOPS
  # instead of 3 IOPS per GB. On a 20GB volume that is 3000 vs 60.
  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage # storage autoscaling ceiling
  storage_type          = "gp3"
  storage_encrypted     = true
  kms_key_id            = local.kms_key_id

  db_name  = var.database_name
  username = var.master_username
  password = random_password.master.result
  port     = 5432

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [var.security_group_id]
  parameter_group_name   = aws_db_parameter_group.this.name
  publicly_accessible    = false

  multi_az = var.multi_az

  # Backups. 7 days of automated snapshots plus PITR within that window is
  # the cheap default; production overrides it to 30.
  backup_retention_period   = var.backup_retention_days
  backup_window             = var.backup_window
  maintenance_window        = var.maintenance_window
  copy_tags_to_snapshot     = true
  delete_automated_backups  = false
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${var.name_prefix}-final-${formatdate("YYYYMMDDhhmmss", timestamp())}"

  deletion_protection = var.deletion_protection

  # Ship Postgres logs to CloudWatch so they sit next to the application logs
  # and can be queried in the same place.
  enabled_cloudwatch_logs_exports = ["postgresql", "upgrade"]

  performance_insights_enabled          = var.performance_insights_enabled
  performance_insights_retention_period = var.performance_insights_enabled ? 7 : null
  monitoring_interval                   = var.enhanced_monitoring_interval
  monitoring_role_arn                   = var.enhanced_monitoring_interval > 0 ? aws_iam_role.monitoring[0].arn : null

  auto_minor_version_upgrade = true
  apply_immediately          = var.apply_immediately

  tags = merge(local.tags, { Name = "${var.name_prefix}-postgres" })

  lifecycle {
    # The final snapshot name embeds a timestamp, which would otherwise show
    # as a diff on every single plan.
    ignore_changes = [final_snapshot_identifier]
  }
}

# ---------------------------------------------------------------------------
# Enhanced monitoring
#
# Gives OS-level metrics from inside the instance (per-process CPU, real
# memory pressure) that the standard CloudWatch metrics do not expose.
# ---------------------------------------------------------------------------

data "aws_iam_policy_document" "monitoring_assume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["monitoring.rds.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "monitoring" {
  count = var.enhanced_monitoring_interval > 0 ? 1 : 0

  name               = "${var.name_prefix}-rds-monitoring"
  assume_role_policy = data.aws_iam_policy_document.monitoring_assume.json
  tags               = local.tags
}

resource "aws_iam_role_policy_attachment" "monitoring" {
  count = var.enhanced_monitoring_interval > 0 ? 1 : 0

  role       = aws_iam_role.monitoring[0].name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}

# ---------------------------------------------------------------------------
# Credential secret
#
# Stored as JSON in the shape RDS itself uses, so rotation via the AWS-provided
# rotation Lambda can be switched on later without changing the consumer.
# ---------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "credentials" {
  name_prefix = "${var.name_prefix}/database/"
  description = "Master credentials for ${aws_db_instance.this.identifier}"
  kms_key_id  = var.create_kms_key ? aws_kms_key.database[0].arn : null

  # Non-zero so a secret deleted by accident can be restored. Set to 0 in
  # throwaway environments where you re-apply repeatedly and hit
  # "a secret with this name is scheduled for deletion".
  recovery_window_in_days = var.secret_recovery_window_days

  tags = local.tags
}

resource "aws_secretsmanager_secret_version" "credentials" {
  secret_id = aws_secretsmanager_secret.credentials.id

  secret_string = jsonencode({
    engine   = "postgres"
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
    dbname   = aws_db_instance.this.db_name
    username = aws_db_instance.this.username
    password = random_password.master.result
  })
}
